
package br.quartzo.soap.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSControleAcessoGPESoapPort", targetNamespace = "br.com.abaco.sisbase")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSControleAcessoGPESoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPESETLOGINResponse
     */
    @WebMethod(operationName = "SETLOGIN", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.SETLOGIN")
    @WebResult(name = "WSControleAcessoGPE.SETLOGINResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPESETLOGINResponse setlogin(
        @WebParam(name = "WSControleAcessoGPE.SETLOGIN", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPESETLOGIN parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPEGETLISTAACAOOBJETOUSUARIOResponse
     */
    @WebMethod(operationName = "GETLISTAACAOOBJETOUSUARIO", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.GETLISTAACAOOBJETOUSUARIO")
    @WebResult(name = "WSControleAcessoGPE.GETLISTAACAOOBJETOUSUARIOResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPEGETLISTAACAOOBJETOUSUARIOResponse getlistaacaoobjetousuario(
        @WebParam(name = "WSControleAcessoGPE.GETLISTAACAOOBJETOUSUARIO", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPEGETLISTAACAOOBJETOUSUARIO parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPEGETMENUGXUIResponse
     */
    @WebMethod(operationName = "GETMENUGXUI", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.GETMENUGXUI")
    @WebResult(name = "WSControleAcessoGPE.GETMENUGXUIResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPEGETMENUGXUIResponse getmenugxui(
        @WebParam(name = "WSControleAcessoGPE.GETMENUGXUI", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPEGETMENUGXUI parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPEGETMENUSISTEMASResponse
     */
    @WebMethod(operationName = "GETMENUSISTEMAS", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.GETMENUSISTEMAS")
    @WebResult(name = "WSControleAcessoGPE.GETMENUSISTEMASResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPEGETMENUSISTEMASResponse getmenusistemas(
        @WebParam(name = "WSControleAcessoGPE.GETMENUSISTEMAS", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPEGETMENUSISTEMAS parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPEGETUSUARIOAUTENTICADOResponse
     */
    @WebMethod(operationName = "GETUSUARIOAUTENTICADO", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.GETUSUARIOAUTENTICADO")
    @WebResult(name = "WSControleAcessoGPE.GETUSUARIOAUTENTICADOResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPEGETUSUARIOAUTENTICADOResponse getusuarioautenticado(
        @WebParam(name = "WSControleAcessoGPE.GETUSUARIOAUTENTICADO", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPEGETUSUARIOAUTENTICADO parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPEGETLISTAOBJETOUSUARIOAUTENTICADOResponse
     */
    @WebMethod(operationName = "GETLISTAOBJETOUSUARIOAUTENTICADO", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.GETLISTAOBJETOUSUARIOAUTENTICADO")
    @WebResult(name = "WSControleAcessoGPE.GETLISTAOBJETOUSUARIOAUTENTICADOResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPEGETLISTAOBJETOUSUARIOAUTENTICADOResponse getlistaobjetousuarioautenticado(
        @WebParam(name = "WSControleAcessoGPE.GETLISTAOBJETOUSUARIOAUTENTICADO", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPEGETLISTAOBJETOUSUARIOAUTENTICADO parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPEGETORGANOGRAMAUSUARIOAUTResponse
     */
    @WebMethod(operationName = "GETORGANOGRAMAUSUARIOAUT", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.GETORGANOGRAMAUSUARIOAUT")
    @WebResult(name = "WSControleAcessoGPE.GETORGANOGRAMAUSUARIOAUTResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPEGETORGANOGRAMAUSUARIOAUTResponse getorganogramausuarioaut(
        @WebParam(name = "WSControleAcessoGPE.GETORGANOGRAMAUSUARIOAUT", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPEGETORGANOGRAMAUSUARIOAUT parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPEVALIDARLOGINACESSOResponse
     */
    @WebMethod(operationName = "VALIDARLOGINACESSO", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.VALIDARLOGINACESSO")
    @WebResult(name = "WSControleAcessoGPE.VALIDARLOGINACESSOResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPEVALIDARLOGINACESSOResponse validarloginacesso(
        @WebParam(name = "WSControleAcessoGPE.VALIDARLOGINACESSO", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPEVALIDARLOGINACESSO parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.quartzo.soap.ws.client.WSControleAcessoGPESETORGANOGRAMAUSUARIOAUTResponse
     */
    @WebMethod(operationName = "SETORGANOGRAMAUSUARIOAUT", action = "br.com.abaco.sisbaseaction/AWSCONTROLEACESSOGPE.SETORGANOGRAMAUSUARIOAUT")
    @WebResult(name = "WSControleAcessoGPE.SETORGANOGRAMAUSUARIOAUTResponse", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
    public WSControleAcessoGPESETORGANOGRAMAUSUARIOAUTResponse setorganogramausuarioaut(
        @WebParam(name = "WSControleAcessoGPE.SETORGANOGRAMAUSUARIOAUT", targetNamespace = "br.com.abaco.sisbase", partName = "parameters")
        WSControleAcessoGPESETORGANOGRAMAUSUARIOAUT parameters);

}
