
package br.quartzo.soap.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSControleAcessoGPE", targetNamespace = "br.com.abaco.sisbase", wsdlLocation = "file:/C:/Desenvolvimento/rocketit/pmc/gpe/awscontroleacessogpe.wsdl")
public class WSControleAcessoGPE
    extends Service
{

    private final static URL WSCONTROLEACESSOGPE_WSDL_LOCATION;
    private final static WebServiceException WSCONTROLEACESSOGPE_EXCEPTION;
    private final static QName WSCONTROLEACESSOGPE_QNAME = new QName("br.com.abaco.sisbase", "WSControleAcessoGPE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Desenvolvimento/rocketit/pmc/gpe/awscontroleacessogpe.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONTROLEACESSOGPE_WSDL_LOCATION = url;
        WSCONTROLEACESSOGPE_EXCEPTION = e;
    }

    public WSControleAcessoGPE() {
        super(__getWsdlLocation(), WSCONTROLEACESSOGPE_QNAME);
    }

    public WSControleAcessoGPE(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONTROLEACESSOGPE_QNAME, features);
    }

    public WSControleAcessoGPE(URL wsdlLocation) {
        super(wsdlLocation, WSCONTROLEACESSOGPE_QNAME);
    }

    public WSControleAcessoGPE(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONTROLEACESSOGPE_QNAME, features);
    }

    public WSControleAcessoGPE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSControleAcessoGPE(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSControleAcessoGPESoapPort
     */
    @WebEndpoint(name = "WSControleAcessoGPESoapPort")
    public WSControleAcessoGPESoapPort getWSControleAcessoGPESoapPort() {
        return super.getPort(new QName("br.com.abaco.sisbase", "WSControleAcessoGPESoapPort"), WSControleAcessoGPESoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSControleAcessoGPESoapPort
     */
    @WebEndpoint(name = "WSControleAcessoGPESoapPort")
    public WSControleAcessoGPESoapPort getWSControleAcessoGPESoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("br.com.abaco.sisbase", "WSControleAcessoGPESoapPort"), WSControleAcessoGPESoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONTROLEACESSOGPE_EXCEPTION!= null) {
            throw WSCONTROLEACESSOGPE_EXCEPTION;
        }
        return WSCONTROLEACESSOGPE_WSDL_LOCATION;
    }

}
